### ISSUE TITLE
Add Sign In with Google React component

### ISSUE THREAD

**Issue by byliuyang** [byliuyang/short#202]
![image](https://user-images.githubusercontent.com/3537801/66273703-141a0c80-e82b-11e9-89d3-589806b2aaa6.png)

**Comment by RonaldoDev** [comment]
Could I get this issue?

**Comment by byliuyang** [comment]
Sure!

**Comment by deschantkn** [comment]
I would like to pick up this task!

**Comment by byliuyang** [comment]
@deschantkn Thank you so much!

**Comment by deschantkn** [comment]
Do you want a separate component to handle google sign in? Or can I add the code for that in `SignIn.tsx`?

**Comment by byliuyang** [comment]
@deschantkn Please extract out code specific to Github Sign In from this component and created individual components for Github & Google sign that reuses the generic sign in button.

**Comment by deschantkn** [comment]
Hello @byliuyang. I have a raised a PR https://github.com/byliuyang/short/pull/212. This is a work in progress, I want your feedback to make sure I am on the right track.

**Comment by byliuyang** [comment]
@deschantkn  Please join this [Slack channel](https://s.time4hacks.com/r/short-slack) to discuss bugs, dev environment setup, tooling, and coding best practices.
