### ISSUE TITLE
Add comment to exported functions, structs, and variables

### ISSUE THREAD

**Issue by dedifferentiator** [byliuyang/short#203]
Code is not documented at all, so that should be fixed.

**Criteria of success:** [golint=100%](https://goreportcard.com/report/github.com/byliuyang/short#golint)

**Comment by byliuyang** [comment]
@dedifferentiator I am so sorry. Let's do it together!

**Comment by dedifferentiator** [comment]
@byliuyang I'd like to, but I'm unfamiliar with many services you use like graphql or react (yes, such people exist) even if I would like to learn them. I don't want to write docs for those areas I'm not good in, but I'll try do my best to document what I understood :)

**Comment by byliuyang** [comment]
@dedifferentiator Can we split the work into two issue so that I can comment services, like GraphQL and React asynchronously?

**Comment by dedifferentiator** [comment]
@byliuyang Could you start documenting from functions in main.go so I could imagine what's going on, then I'll see whether I can do anything useful or not.

**Comment by byliuyang** [comment]
@dedifferentiator Surely.

**Comment by richardbertozzo** [comment]
Hi @dedifferentiator @byliuyang , can i help this one? Has some specific module that is done?

**Comment by byliuyang** [comment]
Hi @richardbertozzo , I’ll review the code and split the work after I got home today!

**Comment by richardbertozzo** [comment]
Alright, i created a PR, with comments in `dep` package. I'll try make in the others packages also.

**Comment by byliuyang** [comment]
@richardbertozzo @dedifferentiator I integrated code climate to help ensure comments are added.

**Comment by byliuyang** [comment]
@richardbertozzo Please join this [Slack channel](https://s.time4hacks.com/r/short-slack) to discuss bugs, dev environment setup, tooling, and coding best practices.

**Comment by byliuyang** [comment]
Done.
