### ISSUE TITLE
Add sample ReCAPTCHA configuration to README

### ISSUE THREAD

**Issue by byliuyang** [byliuyang/short#211]
The current README did not mention how to properly setup ReCAPTCHA in order for new developers to test their new features locally.

## Success criteria
A new developer should be able to setup ReCAPTCHA for local testing with no effort.

**Comment by shade34321** [comment]
Hey, while I was setting up the environment I wasn't sure what to put for these so I took a best guess but I'll put up a PR shortly if you don't mind verifying them for me. Thanks!
