### ISSUE TITLE
Error when build the container using docker-compose

### ISSUE THREAD

**Issue by bigfpanda** [byliuyang/short#214]
From the README:
> Start server
> ```
> docker-compose up
> ```

When I want to build the container using `docker-compose up`. It returns this following error
```
WARNING: The DOCKERHUB_USERNAME variable is not set. Defaulting to a blank string.
Pulling app (/short:)...
ERROR: invalid reference format
```

So I ended up added `DOCKERHUB_USERNAME` variable explicitly when running `docker-compose up` and it sucessfully builds, for instance
```
DOCKERHUB_USERNAME=byliuyang docker-compose up
```

Is this intended?

**Comment by byliuyang** [comment]
@bigfpanda I think it is due to outdated README. Could you please open a pull request to fix the README? Thanks!

**Comment by bigfpanda** [comment]
Sure, I'll work on it
