### ISSUE TITLE
Add GraphQL API to support sign in with Facebook account

### ISSUE THREAD

**Issue by byliuyang** [byliuyang/short#255]
Currently, users can only sign in through with their Github account. Some of the users may not use Github. Adding Facebook sign in option makes Short more accessible.

**Comment by duderman** [comment]
Do you mind if I jump on this one and https://github.com/byliuyang/short/issues/254 ?

**Comment by byliuyang** [comment]
@duderman Sounds good to me.

**Comment by duderman** [comment]
nice :) can you maybe assign them on me?

**Comment by byliuyang** [comment]
Hi @duderman , you need to leave a comment at #254 in order for me to sign the issue to you!
