### ISSUE TITLE
Multi-stage build for frontend and backend

### ISSUE THREAD

**Issue by obukhov** [byliuyang/short#290]
I found out that one can use either image from the hub or pre-build frontend application locally to pack it to docker. 

That means that you have to have yarn installed locally if you make changes to the frontend.

There is a similar problem with backend. Distribution can carry only binary (which will make it much more lightweight) instead of carrying the whole golang sdk.

I would suggest enabling frontend build with docker multi-stage build for frontend (and possibly for backend). I'm working on PR for that.

**Comment by byliuyang** [comment]
@obukhov Thank you so much! Amazing suggestion! We can also completely decouple frontend away from backend when you see fit.

**Comment by byliuyang** [comment]
https://matthiasnoback.nl/2017/04/docker-build-patterns/

**Comment by byliuyang** [comment]
#281
