### ISSUE TITLE
Receive "auth token is invalid" when creating a link

### ISSUE THREAD

**Issue by Coteh** [byliuyang/short#295]
Was trying to get the development environment setup to make a contribution, and opened up the app to make a short link. I authenticated with GitHub, defined a link and clicked "Create Short Link". It asked me to authenticate with GitHub again. I peered into the Network tab and noticed the following response from the `createUrl` GraphQL path:

`auth token is invalid`

I tried the same thing in production and noticed that production was getting the same error, so I decided to post this here. Let me know if you want more info, thanks!

**Comment by byliuyang** [comment]
#192
