### ISSUE TITLE
Add database attribute indicating whether a short link is public

### ISSUE THREAD

**Issue by Coteh** [byliuyang/short#299]
Depends on #235. This attribute can be added as a new column to the `url` table. By default, short links will be private, so this will be set to false by default. This column should also be non-nullable, as we only expect two states (either it's public or it isn't).

**Comment by byliuyang** [comment]
In my opinion, `private` or `public` is not naturally a property of `url`. How about creating a new table called `public_url`?

**Comment by Coteh** [comment]
#307 has been merged.
