### ISSUE TITLE
[Feature] Migrate to OpenID API for Google sign in

### ISSUE THREAD

**Issue by dawntomm** [byliuyang/short#423]
**What is the problem?**
There is no official document for https://www.googleapis.com/oauth2/v3/userinfo as the API endpoint to retrieve user info.  

**Your solution**
Migrating to [OpenID](https://developers.google.com/identity/protocols/OpenIDConnect).

**Alternatives considered**
Keep using current endpoint.

**Comment by byliuyang** [comment]
https://stackoverflow.com/questions/24442668/google-oauth-api-to-get-users-email-address
